# Generated by Django 4.1 on 2024-09-12 19:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='drivers',
            field=models.ManyToManyField(related_name='driver', to=settings.AUTH_USER_MODEL),
        ),
    ]
